### ISSUE TITLE
Unable to use scn::scan with string_view under MSVC.

### ISSUE THREAD

**Issue by nanoric** [eliaskosunen/scnlib#14]
The code from README is unable to compile under MSVC (Visual Studio 2019 16.4.2):
```cpp
#pragma once
#include <string>
#include <string_view>
#include <scn/scn.h>
#include <iostream>

using namespace std;
using namespace std::string_literals;
using namespace std::string_view_literals;

int main()
{
    std::string_view str = "Hello world!"sv;

    std::string word;
    scn::scan(str, "{}", word);

    std::cout << word << '\n'; // Will output "Hello"
    std::cout << str << '\n';  // Will output " world!"
}


```
Error Output:
```
1>Source.cpp
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\range.h(77,1): error C2440: 'return': cannot convert from 'initializer list' to 'std::basic_string_view<char,std::char_traits<char>>'
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\range.h(77,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\range.h(121): message : see reference to function template instantiation 'std::basic_string_view<char,std::char_traits<char>> scn::v0::detail::reconstruct<char,std::char_traits<char>,std::_String_view_iterator<_Traits>,std::_String_view_iterator<_Traits>>(scn::v0::detail::reconstruct_tag<std::basic_string_view<char,_Traits>>,Iterator,Sentinel)' being compiled
1>        with
1>        [
1>            _Traits=std::char_traits<char>,
1>            Iterator=std::_String_view_iterator<std::char_traits<char>>,
1>            Sentinel=std::_String_view_iterator<std::char_traits<char>>
1>        ]
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\range.h(119): message : while compiling class template member function 'std::basic_string_view<char,std::char_traits<char>> scn::v0::detail::range_wrapper<std::string_view &>::range(void) const'
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\range.h(126): message : see reference to function template instantiation 'std::basic_string_view<char,std::char_traits<char>> scn::v0::detail::range_wrapper<std::string_view &>::range(void) const' being compiled
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\range.h(263): message : see reference to class template instantiation 'scn::v0::detail::range_wrapper<std::string_view &>' being compiled
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\range.h(261): message : while compiling class template member function 'scn::v0::detail::range_wrapper<std::string_view &> scn::v0::detail::_wrap::fn::operator ()<std::string_view&>(Range) noexcept const'
1>        with
1>        [
1>            Range=std::string_view &
1>        ]
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\scan.h(32): message : see reference to class template instantiation 'scn::v0::detail::range_wrapper_for<Range>' being compiled
1>        with
1>        [
1>            Range=std::string_view &
1>        ]
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\scan.h(32): message : see reference to alias template instantiation 'scn::v0::detail::range_wrapper_for_t<std::basic_string_view<char,std::char_traits<char>>&>' being compiled
1>C:\Users\Weizehua\source\repos\test_scnlib\test_scnlib\Source.cpp(15): message : see reference to class template instantiation 'scn::v0::detail::scan_result_for_range<std::string_view &,scn::v0::wrapped_error>' being compiled
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\scan.h(73): message : see reference to alias template instantiation 'scn::v0::detail::scan_result_for_range_t<std::string_view&,scn::v0::wrapped_error>' being compiled
1>C:\projects\vcpkg\installed\x64-windows\include\scn\detail\scan.h(135): message : see reference to function template instantiation 'scan_result_for_range<Range,scn::v0::wrapped_error>::type scn::v0::scan(Range &&,scn::v0::detail::default_t,Args &...)' being compiled
1>Done building project "test_scnlib.vcxproj" -- FAILED.
```

It seems std::basic_string_view don't accept an iterator and a length as arguments.
std::basic_string_view can only construct from (char *, size_t),  So this forum is accetable:
```cpp
// range.h #77:
// distance uses end - begin, which is unsupported for std::string_view with different range in DEBUG mode.
            return {&*begin, static_cast<size_t>(std::to_address(end) - std::to_address(begin))};
```

BTW, I guess the test case inside string_view.cpp should construct an run time string(std::string, raw string buffer, etc) instead of passing a compile-time string literal as first argument to scn::scan. Because nobody needs a library that scans from compile-time string.

**Comment by nanoric** [comment]
It seems all the code should run correctly under Release mode.
But under Debug mode, whenever you operate an iterator with another one, such as
```
auto raw = "123456";
std::string_view s(raw);
std::string_view s(raw+2);
s.begin() - s2.begin();  // _STL_VERIFY fails:
/*
code in xstring:
    _NODISCARD constexpr difference_type operator-(const _String_view_iterator& _Right) const noexcept {
#if _ITERATOR_DEBUG_LEVEL >= 1
        _STL_VERIFY(_Mydata == _Right._Mydata && _Mysize == _Right._Mysize,
            "cannot subtract incompatible string_view iterators");
        return static_cast<difference_type>(_Myoff - _Right._Myoff);
#else // ^^^ _ITERATOR_DEBUG_LEVEL >= 1 ^^^ // vvv _ITERATOR_DEBUG_LEVEL == 0 vvv
        return _Myptr - _Right._Myptr;
#endif // _ITERATOR_DEBUG_LEVEL
    }

*/
```


MSVC will check if s and s2 points to the same buffer and have the same size. If not, exception is thrown.
Thus, the ranges intenally used by scn is not compatible with MSVC's std::string_view under Debug mode. Because write_return function will construct a new ranges(std::string_view), making all operators for iterator invalid.

**Comment by eliaskosunen** [comment]
Aw bugger, it's those MSVC debug iterators again. I'll look into this on ~Monday, once I have access to a Windows PC.

**Comment by eliaskosunen** [comment]
Fixed in 5b2eb91. Thanks for reporting!

**Comment by nanoric** [comment]
MSVC under Debug mode still not work.
The test string_view.cpp fails.
![image](https://user-images.githubusercontent.com/6782307/71830793-78769180-30e2-11ea-9213-d31757876fdb.png)
![image](https://user-images.githubusercontent.com/6782307/71830804-7f050900-30e2-11ea-9340-dcb71323c618.png)

**Comment by nanoric** [comment]
It seems that under MSVC debug mode(_ITERATOR_DEBUG_LEVEL >=1), you must change the range recursively after calling write_return.

**Comment by nanoric** [comment]
How can I re-open this issue?
Or should I create a new issue?

**Comment by eliaskosunen** [comment]
I can't get that assertion to fire on my Windows PC nor on Appveyor. Can you see if it does for you after 8b3ab27?

**Comment by nanoric** [comment]
Maybe I forgot to pull updated code. The test passed. Everything works fine for now.
